pipeline{
    agent any
    options{
        timestamps()
    }
    environment{
        artifactory_creds=credentials("artifactory-creds")
        artifactory_registry="docker-images-docker"
        ARTIFACTORY_URL="https://nidhithakkar.jfrog.io/"
    }
    stages{
        stage("fetch version"){
            steps{
                script{
                    version = readFile(file: "version.txt").trim()
                }
            }
        }
        stage("create docker image"){
            steps{
                script{
                    dockerImage=docker.build("$env.artifactory_registry/maven-image-with-app:$version", "--build-arg ARG1=HELLO")
                }
            }
        }
        stage("push docker image to artifactory"){
            steps{
                script{
                    docker.withRegistry("$env.ARTIFACTORY_URL/$env.artifactory_registry", "artifactory-creds"){
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
